import "server-only";

/**
 * Paid continuations, keyed by on-chain contentId.
 *
 * This module is server-only: it never ships to the client bundle. The paid
 * paragraphs are released exclusively by the API route, and only after the
 * paywall has verified the reader's entitlement against TollgateAccessRegistry
 * on Arbitrum. The client literally does not possess this text until it pays.
 */
export const PAID: Record<string, string[]> = {
  // The Price of Attention
  "0x9a1d2c3b4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f9": [
    "Consider the micropayment, that perennial punchline of the early internet. For thirty years it failed for the same boring reason every time: the friction of paying cost more than the thing being paid for. A nickel article behind a checkout flow is not a nickel article. It is a nickel article plus a password, plus a card number, plus a moment of doubt — and the doubt alone is worth more than the nickel.",
    "So the micropayment did not die of bad economics. It died of bad interface. The number was always reasonable; the ceremony around it was not. Every previous attempt asked the reader to become, briefly, an accountant. To stop being a person enjoying a sentence and start being a person approving a transaction.",
    "The fix, when it finally arrived, did not look like a payment at all. It looked like the absence of one. You tap a word and the rest of the page simply arrives, the way a door you have a key to does not announce itself as a door. The money moved. You were not asked to witness it move. The receipt exists, exactly, for the one time in a thousand you want to look.",
    "This is the part the builders keep getting wrong, so let me be unfashionably blunt about it. The goal is not to show the user the blockchain. The goal is to show the user the story. Every chain selector, every gas estimate, every 'approve in your wallet' is a confession that the plumbing has leaked into the room. The triumph is a dry floor.",
    "And when the floor is dry — when paying for a paragraph costs a paragraph's worth of thought and no more — something strange comes back to life. Not the paywall, that grim portcullis. Something older. The newsstand. A place where small money buys small pleasures, one at a time, with no subscription, no lock-in, and no sermon. We are about to find out if we still know how to build one.",
  ],
  // The Logistics of Forgetting
  "0x1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f901": [
    "My guide for the first week was a systems engineer who asked to be called Ramon, which was not his name, and who had the specific calm of a person who has made peace with a contradiction. His job was to honor deletion requests. His job was also to ensure that nothing was ever truly destroyed without a ninety-day window, three jurisdictions of legal hold, and a backup of the backup.",
    "'People think delete is a verb,' he told me, on the third day, eating a sandwich over a console that listed forty thousand pending erasures. 'It's a request. You're asking a very large number of machines to agree to lose something at the same time. They mostly do. Mostly.'",
    "The word 'mostly' did a great deal of work in that room. It was in the air conditioning and the legal language and the resigned jokes. Every system I was shown was designed to forget, and every system had a second system behind it designed to remember just in case forgetting turned out to be a mistake. The redundancy was not malice. It was fear of the lawsuit, the regulator, the catastrophe — fear dressed up as prudence and stored at four degrees Celsius.",
    "What unsettled me was not that the data survived. It was the tenderness of the people maintaining it. They spoke about old accounts the way archivists speak about letters: with a custodial gentleness entirely out of proportion to the spreadsheets involved. One technician kept what she called 'the orphans,' fragments of profiles whose owners had died, in a directory she could not bring herself to purge. Nobody had asked her to keep them. Nobody had asked her to stop.",
    "By the end I had stopped believing in deletion the way I had stopped believing in a flat horizon: not because it was false, exactly, but because it described a convenience rather than a fact. We do not erase. We agree to look away, in concert, and we pay people like Ramon to maintain the choreography of that looking-away — and to break it, instantly, the moment someone with standing demands the thing back.",
  ],
  // The Interface Is the Argument
  "0x2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f9012a": [
    "Take the confirmation dialog, that small grey tombstone of trust. 'Are you sure?' is not a question. It is an admission. It says: we built a thing dangerous enough that we no longer trust ourselves to have built it safely, so we are deputizing your anxiety as our last line of defense. Every 'are you sure' is a bug that won an argument with a deadline.",
    "Now take its opposite, the interaction so well-made that it removes the question entirely. The undo. The undo is the most humane idea in the history of software because it makes the same claim in reverse: act freely, we have you, nothing here is fatal. A product full of confirmations is a product that fears you. A product built on undo is a product that respects you. They are doing the same job. They could not be more different.",
    "This is why I have come to judge payment flows the way I judge sentences. A good sentence does not show you its grammar. A good payment does not show you its rails. The moment a checkout asks me to select a network, approve a contract, and estimate a fee, it has switched from prose to footnotes, and footnotes are where arguments go to apologize.",
    "The best interfaces I know share a single discipline: they refuse to make their hardest problem into your problem. The cross-chain routing, the gas, the settlement — that is the maker's burden, and a maker who hands it to the reader has not finished the work, only relabeled the unfinished part as a 'feature.' Difficulty is not honesty. Sometimes difficulty is just a confession you decided to charge admission for.",
    "So here is the test, and it costs nothing to apply. Watch where a product puts its complexity. If it pushes the hard part toward itself, quietly, and gives you back something that feels like ease — that is a product with a thesis it is willing to defend. If it pushes the hard part toward you and calls it transparency, it has no thesis. It has a backlog, and a marketing department, and a hope that you will mistake the two.",
  ],
  // Small Money
  "0x3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f9012a3b": [
    "Consider what a tip is. It is not payment; the service was already rendered and, usually, already paid for. A tip is a second, optional sentence appended to a transaction, and like all optional sentences it carries the entire weight of meaning precisely because it could have been left out. To tip is to say: I noticed. The noticing is the gift; the money is only its handwriting.",
    "The internet promised to make this universal and instead made it grand. Every platform that lets you support a maker turns the coin into a commitment: a subscription, a membership, a monthly siphon you will forget to cancel. These are not tips. They are marriages. And most of what we encounter — the good thread, the right answer, the small mercy of a stranger's competence — does not warrant a marriage. It warrants a coin.",
    "What killed the coin was arithmetic. Moving a quarter used to cost more than a quarter, so nobody moved quarters, so the quarter-sized gesture simply ceased to have a vehicle. The gesture did not die of indifference. It died of overhead, which is a sadder and more fixable death.",
    "I find I am sentimental about the fix in a way I did not expect. When the cost of saying 'I noticed' falls back to roughly the cost of the noticing itself, a whole vocabulary returns. You can pay a writer a quarter and mean it. You can pass a coin to a stranger's good work and move on without ceremony. The small money comes back, and with it the small, constant, civilizing habit of registering that other people are good at things.",
    "My grandfather would not have understood a word of how it works, and he would have understood the whole of what it is for. Put your hand in your pocket. Find the smallest thing in there. Give it to the person who just made your day fractionally better. That is the entire civilization, and we very nearly engineered it out of existence by accident.",
  ],
  // The Quiet Rail
  "0x4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f9012a3b4c": [
    "The pattern repeats with the grim regularity of a fable. A new settlement technology arrives, genuinely better in some deep way, and its earliest products cannot stop talking about it. They put the technology in the name. They put it on the button. They make the user say its words back to them before any value will move. And they fail, not because the technology is bad, but because they have confused the achievement with the advertisement.",
    "Then a second wave arrives, built by people who are slightly embarrassed by the first. They take the same technology and they bury it. They make the button say what the user wants — 'unlock,' 'send,' 'tip' — and they make the machinery answer in silence. Their marketing barely mentions the breakthrough underneath. And these are the products that win, every time, in every cycle, going back further than the internet.",
    "The lesson is not 'hide the technology' in the cynical sense, as if the goal were concealment. The lesson is that adoption is a measure of disappearance. A thing has been adopted precisely to the degree that people have stopped noticing it. You can chart the maturity of any rail by how rarely its users say its name, and the destination — the actual finish line — is a kind of total invisibility that feels, from the inside, simply like things working.",
    "This puts the honest builder in an odd emotional position. The closer you get to success, the less credit your cleverest work can receive, because its cleverness is expressed as the user's obliviousness. You spend enormous effort routing value across chains, sponsoring gas, abstracting accounts — and the entire reward for doing it well is that no one will ever know you did it at all. The applause goes to the smooth surface. The engineering lives in the quiet.",
    "I have made my peace with this, mostly, and I think anyone building in this decade will have to. The work that matters now is not the loud kind. It is the patient construction of rails so quiet that the people riding them will argue, sincerely, that nothing technical is happening here at all — that they are simply reading, simply paying, simply living. When they say that, and believe it, you will know the rail is finished. And almost no one will thank you, which is exactly how you will know it worked.",
  ],
};
